### PR TITLE
Add SASL Bind support (currently only CRAM-MD5)

### PR DESCRIPTION
**Pull request by mstum**
The original Novell client had the beginnings of SASL Authentication in the form of SaslBindProperties/SaslBindCallbackHandler, but didn't actually implement anything. They've added the missing bits in further updates to the Java library, but never ported them to the C# one.

This here adds SASL support by adding a  `Bind(SaslRequest saslRequest)` method to LdapConnection, an `ISaslClientFactory` that creates the actual `ISaslClient` that handles the handshake, and a `CramMD5Client` that handles CRAM-MD5 authentication.

I am still working on DIGEST-MD5 and GSSAPI/Kerberos, and there are plans for a few more cleanups, but this provides the plumbing and extensibility needed.

I've also added a Unit Test project, because the FunctionalTests project is running integration tests against an LDAP Server.

Because I'm using a helper function from another MIT-Licensed project, I've added a NOTICE.md for proper attribution. I'm not sure what the proper attribution for the entire project should be, but since the new code is heavily modeled after Novell's Java LDAP Library anyway, having it all attributed to Novell is still good, I think.

### CODE REVIEW

**Comment by dsbenghe** [comment]
This is a great contribution. Did you test it against any ldap server? 

Ideally we will want an integration test to test this feature - probably most of the effort for this will be in setting up openldap (which is used for integration tests) to accept this type of SASL authentication. But I understand if this is not your thing :)

**Comment by mstum** [comment]
Yes, I'm developing this (and all future PRs/changes) against several actual LDAP Servers, specifically Windows Server 2016 Active Directory, macOS High Sierra Server OpenDirectory, PingIdentity Directory and OpenLDAP on Debian 9 stable. Later on, I'll also test against Azure AD to (hopefully) cover all use cases and vendor-specific ~~nonsense~~differences.

It's actually the macOS case that brought me down this path first, because by default, it only supports CRAM-MD5 or Kerberos, but not DIGEST-MD5 - hence the .net built in LDAP stuff couldn't connect unless I set up Kerberos or was OK with Simple Bind (which I am not, even over LDAPS or StartTLS)

I do want to set up an OpenLDAP Server automatically for automated testing in the Product I'm integrating it with, but right now I don't really have anything here since adding the functionality first is more important. That said, does your Travis or Appveyor build have a VM available? I could set one up on Azure otherwise, though that'll be later in the week.

I'd classify SASL Support right now as "WIP"/experimental, simply because adding remaining mechanisms (DIGEST-MD5, Kerberos v5, potentially SPNEGO) might result in some API changes/cheese-moving. But the code as-is works fine against my test servers.

**Comment by dsbenghe** [comment]
Travis build is running on the travis ubuntu trusty VM and runs the tests against openldap (openldap is installed and setup by the build script at the start of the build - which I have in plan to extract it in a shell script so it can be used outside travis context). 

AppVeyor build is running on windows and doesn't run the tests - main reason being no ldap server available and was easier to setup and configure a openldap server on linux  :) (and is also the server I'm running for developing).

The master branch is work in progress (and marked as 3.0) and has already breaking api changes so there is no issue in putting more wip there.

**Comment by mstum** [comment]
Ok. In that case, there'll be a few more PRs coming in over the next few days (see #60), with Kerberos following sometime next week if everything goes to plan (Needing to add functionality to the ASN.1 stuff for that).

I'll see how OpenLDAP would need to be configured to offer SASL mechanisms without sacrificing anything else, once I have that I can just open an issue with my config settings so that the Travis build could be updated?

**Pull request merged**
