### PR TITLE
Implemented async methods

### LINKED ISSUE #27: Implement async methods
Version 2.3.7 used

For now all kind of API is totally synchronous, no Task<T> used.
Underlying .net core asynchronous methods decorated with .WaitAndUnwrap() and .ResultAndUnwrap()

API should be refactored to support methods returning Task (ConnectAsync, BindAsync, etc).

### PR DESCRIPTION
**Pull request by wslyhbb**
Fixes #27

### CODE REVIEW

**Comment by dsbenghe** [comment]
What will be the reason to keep the sync versions and implement it via wrapping of the async ones? 

I know that this will break the existing interface but that should be expected when going async. Getting rid of the wrapping will also make it clear where are still problems in going async.

**Comment by wslyhbb** [comment]
Hi,
I did it for two reasons:
1. Backward compatibility
- If someone updates the library it does not break their code and they do not have to change a bunch of code.
2. From what I have seen, this appears to be industry standard
For example:
- the low level Socket has Connect and ConnectAsync, Send and SendAsync, Receive and ReceiveAsync
- Stream has Read and ReadAsync, Write and WriteAsync, Flush and FlushAsync,
- DbConnection which both SqlConnection and MySqlConnection implement have an Open and OpenAsync
- DbCommand has both versions of every Execute method
   - ExecuteDbDataReader/ExecuteDbDataReaderAsync
   - ExecuteNonQuery/ExecuteNonQueryAsync

However, I have also seen where there is only async methods:
- SslStream and HttpClient

**Comment by dsbenghe** [comment]
You can be sure that the apis which have both async and sync versions are not implementing the sync version by blocking on the async version, as this is not recommended approach.

If someone wants, it can easily implement sync wrappers on top of the async => but is their choice: how to implement it and knowing the risks of that.

As I said, I don't see the breaking change as a stopper - that is why we have major versions for.

**Comment by dsbenghe** [comment]
FYI - the stress tests are failing massively after this change
https://travis-ci.org/dsbenghe/Novell.Directory.Ldap.NETStandard/builds/659598700
https://travis-ci.org/dsbenghe/Novell.Directory.Ldap.NETStandard/builds/652720557

**Comment by wslyhbb** [comment]
Thanks for letting me know. I am looking into it.

**Comment by wslyhbb** [comment]
Unfortunately, I don't really know what the issue is.

**Comment by dsbenghe** [comment]
Your PR triggered me to look into this. I tried to start using your code, unfortunately, in the meantime, you did a push force on your master and the async code was gone.

Anyway, the develop branch has now async implemented and published as nuget package 4.0.0-alpha1. There are 3 calls still blocking via Result. Feel free to take a look and PR other improvements.

**Comment by wslyhbb** [comment]
Wow, that is great!

**Comment by wslyhbb** [comment]
One suggestion I would make is to replace all of the ArrayLists with at least List<object>. Microsoft, "we recommend that you use the generic List<T> class." - https://docs.microsoft.com/en-us/dotnet/api/system.collections.arraylist?view=netcore-2.2
DE0006: Non-generic collections shouldn't be used - https://github.com/dotnet/platform-compat/blob/master/docs/DE0006.md

I will send you a pull request. Btw, I noticed you have both develop and async branches and async has more commits since master on it. So I assume async is newer so I will send pull request on it.

**Pull request closed without merging**
