### PR TITLE
Utf surrogate fix

### PR DESCRIPTION
**Pull request by ubik**

### CODE REVIEW

**Comment by ubik** [comment]
@dsbenghe Could we integrate this patch ?

**Comment by dsbenghe** [comment]
Can we improve the tests to check also the other cases which were affected by this change are still working correctly?

**Comment by ubik** [comment]
> Can we improve the tests to check also the other cases which were affected by this change are still working correctly?

I add some tests, found 3 bugs in `RfcFilter` `FilterToString` or `ParseFilter` not related to my changes (I have run it on original code witha same result). These tests are marked as skipped.

**Comment by dsbenghe** [comment]
Thanks for your effort/fix. 

Feel free to create more PRs with improvements/fixes :)

**Pull request merged**
