### PR TITLE
Add "Disconnect" method to ILdapConnection interface

### PR DESCRIPTION
**Pull request by matteo-mosca**
Fixes issue #10

### CODE REVIEW

**Comment by matteo-mosca** [comment]
Seems like your travis configuration has some problems. It failed on a "apt-get" command:

`The command "sudo apt-get update -qq" failed and exited with 100 during .`

It has nothing to do with the change.

**Comment by dsbenghe** [comment]
Looks like a recent issue with travis ci - https://github.com/travis-ci/travis-ci/issues/7332 - it is supposed to be fixed - but looks that is not fully fixed.

**Comment by dsbenghe** [comment]
More recent and specifically related with .net core builds - opened 4 hours ago - https://github.com/travis-ci/travis-ci/issues/7565 - I guess we will need to wait for the issue to be fixed.

**Comment by matteo-mosca** [comment]
Agreed, but it has nothing to do with my proposed change. Do you agree in fixing the ILdapConnection interface?

**Comment by dsbenghe** [comment]
I'm ok with the change.

**Pull request merged**
