### PR TITLE
migrate to .net standard 2.0

### PR DESCRIPTION
**Pull request by tomchavakis**

### CODE REVIEW

**Comment by dsbenghe** [comment]
what will be the reason to move the library to .net standard 2.0 instead of 1.3? 1.3 covers more platforms and I specifically went as low as possible regarding the .net standard version.

**Comment by tomchavakis** [comment]
.NET Standard 2.0 supports .NET Core 2.1.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard
I use Novel to a .Net Core 2.1 Project so it is mandatory to migrate this library to .net standard 2.0.

**Comment by dsbenghe** [comment]
The link you sent explains how it works 

> The various .NET implementations target specific versions of .NET Standard. Each .NET implementation version advertises the highest .NET Standard version it supports, a statement that means it also supports previous versions

 e.g. .NET Core 2.0 targets .NET Standard 2.0 which is the highest version supported by .NET Core 2.0 - but supports also all the previous versions (e.g. 1.3 < 2.0)

Looking at the table found at the link you quoted - the library. being built on .net standard 1.3, will work without problems on .net core >= 1.0, .net framework >= 4.6

Do you get any error? it works fine for me.

**Comment by tomchavakis** [comment]
No I didn't get any error. You can use Version .NET Standard 1.3 at .NET Core 2.1, i thought that the minimum is .NET Standard 2.0, but it is nice to have the option for 2.0 for future purposes.

**Comment by dsbenghe** [comment]
In the end, I cherry picked your changes and squashed them in one and made some more changes and now the nuget package contains two versions of the library: one for net standard 1.3 and one for net standard 2.0 - see here https://www.nuget.org/packages/Novell.Directory.Ldap.NETStandard/3.0.0-beta3. It is true that while the 1.3 works also, the net standard 2.0 version may make it easier for people to use the package in some cases.

**Pull request closed without merging**
